### ISSUE TITLE
Details on what's missing?

### ISSUE THREAD

**Issue by RobertLowe** [meteor-useraccounts/polymer#1]
Hey, I just set this up quick and it looks good.

A couple things mentioned in the README.md are still missing (such as social buttons being clickable `button != paper-button`).

Could you go into a little detail about these:

-text input
-checkbox input
-select input
-radio input
-hidden input

Cheers

**Comment by splendido** [comment]
Hi @RobertLowe,
I'm sorry I'm still not up to date with this part of the project...

We need an input from @kevohagan! ;-)

**Comment by splendido** [comment]
...looking at the [input templates](https://github.com/meteor-useraccounts/polymer/blob/master/lib/at_input.html) it seems that the only one being updated for polymer is the `text` input.

The hidden input shouldn't need any changes...

**Comment by splendido** [comment]
I've just made the social button click working: see 6057af97a67e4841d3e1ddf7991b98733ba4e273

**Comment by kevohagan** [comment]
hey guys!

yes this is definitely on my list to update, ill udpate all of this
tomorrow.

@RobertLowe thanks for the feedback, any other thing that you see just let
me know!

Thanks @splendido for the commit! ( i didnt even check you could inherit
events from AT like that!) , this might also work for the submit button of
the at_pwd_form! ill check it out

On 25 January 2015 at 16:39, Luca Mussi notifications@github.com wrote:

> I've just made the social button click working: see 6057af9
> https://github.com/meteor-useraccounts/polymer/commit/6057af97a67e4841d3e1ddf7991b98733ba4e273
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/meteor-useraccounts/polymer/issues/1#issuecomment-71377738
> .

## 

Kevin O'Hagan
@kevohagan
+0034685245319
Palma de Mallorca,
Spain

**Comment by splendido** [comment]
@kevohagan, this _inheritance_ trick was the basis on which AT spinned off ;-)

As for the at_pwd_form_btn: I gave it a quick try but the thing is what is picked up is the [form submit event](https://github.com/meteor-useraccounts/core/blob/master/lib/templates_helpers/at_pwd_form.js#L21) and **not** the `button click`.

If you manage to make the `paper-button` triggering a form submit event, that's it!
...differently you can inherit the `AccountsTemplates.atPwdFormEvents["submit #at-pwd-form"]` event handler for the `click paper-button`
...but make sure you give the `at-btn` if to the paper-button and get rid of the hidden one ;-)

**Comment by RobertLowe** [comment]
@splendido re: 6057af9

Hmm, that's interesting, wouldn't it be simpler to use a `selector`: (ex: `+  'click .social-button': function(){}`?

`polymer` elements behave like normal `HTMLElement`s

---

As for `paper-button` as a submit button; currently it [doesn't support](https://github.com/Polymer/paper-button/issues/14) `type=submit`.

You can also stuff a `<button>` like [this](http://stackoverflow.com/a/27649347) but requires styling however it saves from scripting.

Another option is to capture the `click` event and trigger a `submit` event. Kinda like [this](https://github.com/meteor-useraccounts/polymer/blob/master/lib/at_pwd_form_btn.js#L6-L9) but without the button.

```
'click #at-btn-polymer': function(event,template) {
    event.preventDefault();
    template.$('#at-btn-polymer').trigger('submit');
}
```

Triggers & event handlers are also useful for `child` -> `parent` communication. For instance I could trigger a custom event: `template.$('#thing').trigger('some-thing-special-happened')` and the parent template could have a handler for that. 

Cheers

**Comment by SylarRuby** [comment]
Noob question...sorry...but where do I go to customise the "atForm" template?
