### ISSUE TITLE
Core Icons outdated

### ISSUE THREAD

**Issue by RobertLowe** [meteor-useraccounts/polymer#2]
`core-icons` removed all the `post-*` as they rebased against the open source set from Google.

https://github.com/meteor-useraccounts/polymer/blob/master/lib/at_social.html#L3

http://stackoverflow.com/questions/28153341/were-post-icons-remove-in-core-icons-social-icons-html

https://github.com/Polymer/core-icons/commit/1e94a1175f7b97cb58ef54ecd5ca07c04053bc92#diff-8ea02ad880d928a495d723bd3c6d9978L39

:(

**Comment by kevohagan** [comment]
you are absolutely right @RobertLowe ! I had not catched that at all! 

Do you have a suggestion on what we should do ?

**Comment by splendido** [comment]
Any news on this?

**Comment by splendido** [comment]
ping

**Comment by ThaumRystra** [comment]
These icons are no longer used as of #10

**Comment by splendido** [comment]
should we close this then?

**Comment by ThaumRystra** [comment]
Yeah it should be closed. There is still a problem with icons, but it's a different problem which might have been fixed when PolymerElements/iron-icons#18 was closed, but I need to check.

**Comment by splendido** [comment]
thanks guys
