### ISSUE TITLE
Polymer input validation

### ISSUE THREAD

**Issue by rdrey** [meteor-useraccounts/polymer#5]
Hey everyone

The package is working great for me (functionality wise). The only issue I have is cosmetic.

The input element's error messages are not displayed under the paper-input box for me, instead ending up above the input elements in `<div class="at-error">`

I'm sure I'm not configuring it right, could you add a section on how to set this up to the readme, please?

Thanks a lot!

**Comment by splendido** [comment]
Hi @rdrey,

Simply add the following to the UserAccounts configuration:

``` javascript
AccountsTemplates.configure({
    negativeValidation: true,
    positiveValidation:true,
});
```

This is something already set for the [boilerplate](https://github.com/meteor-useraccounts/boilerplates/tree/master/polymer)

**Comment by rdrey** [comment]
Hi @splendido 

perfect, thanks! I had turned on 'continuousValidation' but not those two settings.

I didn't know about the boilerplates repo at all, that will come in handy if I need a reference again.

Enjoy!

**Comment by splendido** [comment]
glad it worked!
tnx
