### ISSUE TITLE
Fix boilerplate so that we can deploy to useraccounts-polymer.meteor.com

### ISSUE THREAD

**Issue by splendido** [meteor-useraccounts/polymer#6]
See [the boilerplate](https://github.com/meteor-useraccounts/boilerplates/tree/master/polymer)

It seems there's currently some problem with the menu (at least from a desktop PC).
I'd like to get this fixed before deploying to useraccounts-polymer.meteor.com.

@meteor-useraccounts/polymer?

**Comment by kevohagan** [comment]
ill have a look :) thanks for the heads up @splendido!

**Comment by kevohagan** [comment]
@splendido i updated the menu a bit, put some white background and made the
drawer work nicely on smaller screens. was that the issue? let me know,
anyway i seriously need to get up to date with the useraccoutns:polymer
package?

**Comment by splendido** [comment]
ok, I've just realized that there's no `atNavButton` in the navbar...
...I thought there was some problem because it was not 'visible' :(

So the only thing we miss is a link to `sign in` or 'register' in the navbar or wherever it's best.
...sorry!

Could you add it?
...after this I'd say we can deploy  :)

**Comment by splendido** [comment]
...I've just pushed a version with useraccounts@1.7.0

**Comment by jcchin** [comment]
Thanks for making this package! It's awesome, but I fired up the polymer boilerplate and the default resetPassword route seems to be busted...

More specifically, If I navigate to:
http://localhost:3000/reset-password/ko655R968qO5c47qhfbPPcUc_Y7xQ4HNQvMe7byKMRk
It just shows a blank page (not the pageNotFound page...) with an error
 Uncaught TypeError: Cannot read property 'resolveDom' of undefined

To double-check I'm not just crazy, I tried the same route with the bootstrap boilerplate, and the reset-password route worked fine.

**Comment by jcchin** [comment]
I also just tried meteor run android-device (on a Moto X 1st Gen) on the polymer boilerplate.
The "private" route doesn't seem to be working at all on mobile. Seems to stay on the "home" route, can't even access the accounts signup page.

Again as a sanity check, I tried the bootstrap boilerplate version on my device, and it worked fine.

**Comment by splendido** [comment]
Thanks for reporting @jcchin!

We'll have to understand whether this is a problem with the boilerplate structure or with the `useraccounts:polymer` package.

May I ask if you have a chance to test the package on itself on a different polymer project?

**Comment by kevohagan** [comment]
okay ill have a look into this! Thanks @jcchin for the heads up

**Comment by jcchin** [comment]
sure I can poke around a bit more next weekend. I'm new to polymer/bower, but the boilerplate html seemed fairly straightforward, I'd be surprised if that was the main issue. There are a few other packages used in the boilerplate that might potentially be causing some of the issues as well?

Checking the differential team's polymer demo,
(https://github.com/Differential/polymer-demo/blob/master/.meteor/packages)
 they didn't use any polymer atmosphere packages, they did however use "vulcanize" to combine all the component imports (which is definitely desirable). Would the `useraccounts:polymer` package work well with that?

**Comment by jcchin** [comment]
looks like the dependency on the ecwyne:polymer package is the source of the android-device issue:
https://github.com/ecwyne/meteor-polymer-elements/issues/10

**Comment by jcchin** [comment]
the android-device issues can be fixed by using a different (up-to-date) meteor package.
`meteor remove ecwyne:polymer`
`meteor remove ecwyne:polymer-elements`
`meteor add boxxa:polymer`
`meteor add boxxa:polymer-elements`
`meteor run android-device`

(this will not fix the original issue with reset-password)

**Comment by splendido** [comment]
@jcchin, I've just tried the other packages but I get this error log:

```
I20150318-10:31:34.610(1)? installing polymer into public directory...
W20150318-10:31:35.231(1)? (STDERR)           
W20150318-10:31:35.232(1)? (STDERR) /home/lmussi/.meteor/packages/meteor-tool/.1.0.43.1rcpxfn++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:278
W20150318-10:31:35.232(1)? (STDERR)                         throw(ex);
W20150318-10:31:35.232(1)? (STDERR)                               ^
W20150318-10:31:35.250(1)? (STDERR) polymer: Unable to find suitable version for polymer
```

**Comment by splendido** [comment]
...plus, with the current version, is I run `meteor`, nothing is loaded on the client and this is the (first) error I get on the browser's console:

```
Uncaught Error: You tried to use polymer without loading it first. To load polymer, <link rel="import" href="components/polymer/polymer.html">
```

what's happening here?

**Comment by splendido** [comment]
ping

**Comment by ThaumRystra** [comment]
The boilerplate needs to be Polymer 1.0 as well when #9 is done, so I'm having a go at it as well while I attempt #9.
