### ISSUE TITLE
Migrate to Polymer 1.0

### ISSUE THREAD

**Issue by ThaumRystra** [meteor-useraccounts/polymer#9]
Now that Polymer is 1.0, will this package get an update?

**Comment by splendido** [comment]
I'm in the middle of a complete refactor of `useraccounts`.
I don't think I'll have time to look at this for a while... :(

Would you be willing to create a PR for this?
@meteor-useraccounts/polymer?

**Comment by ThaumRystra** [comment]
I'm migrating my current project to Polymer 1.0 so I'll happily do useraccounts as well while I'm at it and submit a PR when it's done. No guarantees on the timeline though.

**Comment by splendido** [comment]
:+1: 
no worries for the timeline, you're welcome to contribute.

Thanks!

**Comment by udiedrichsen** [comment]
Would be great to have useraccounts with Polymer 1.0 :+1:

**Comment by splendido** [comment]
@meteor-useraccounts/polymer?

**Comment by itsashis4u** [comment]
@ThaumRystra Can you migrate it to Polymer v1.0? I am thinking of using the package.

**Comment by a4xrbj1** [comment]
I would second that request from @itsashis4u . Any chance someone can migrate it to Polymer 1.0?

@ThaumRystra Stefan?
@splendido Luca, any update on the refactor?

**Comment by kevohagan** [comment]
i for myself am not planning to work on this package in the foreseable
future, i've dropped Polymer with Meteor all together.

but never say never, we never know, might come back some day :)

**Comment by splendido** [comment]
Hi all, I tried to make the update a couple weeks ago, but I had some problem figuring out wich package to use to test with polymer 1.0.
I tried [boxxa:polymer](https://atmospherejs.com/boxxa/polymer) but got [this issue](https://github.com/boxxa/meteor-polymer/issues/6).
Do you know whether [ecwyne:polymer](https://atmospherejs.com/ecwyne/polymer) is up to date and working?
Which package are you using to get polymer@1.0?

**Comment by splendido** [comment]
@kevohagan am I understanding it right? No more Meteor?!

**Comment by kevohagan** [comment]
NOooooo never!! I will never drop meteor, just not Meteor + Polymer! ;)

**Comment by a4xrbj1** [comment]
Well, close to give up on Meteor on front-end as well as it doesn't seem to
work well with Polymer which is more important for me.

I don't understand why you guys are focussing so much on Angular (which is
about to change and so out of fashion). At least I understand the focus on
the new darling React.js

**Comment by kevohagan** [comment]
Yes, there has not been a good solution for Meteor + Polymer yet...
I disagree with you, even though I haven't tried Angular 2 , from what i've
seen it's not going to be out of fashion.
And React is definitely great news, so easy to work with, plus react native
is very promising.

**Comment by itsashis4u** [comment]
@splendido I am using [loneleeandroo:polymerize](https://atmospherejs.com/loneleeandroo/polymerize) to include Polymer 1.0 and replace Shady DOM with Shadow DOM. It somewhat works.

Also, [ecwyne:polymer](https://atmospherejs.com/ecwyne/polymer) doesn't feel like updated to 1.0.
I had used [boxxa:polymer](https://atmospherejs.com/boxxa/polymer) but then I ran into some errors and had to remove it.

**Comment by ThaumRystra** [comment]
> I would second that request from @itsashis4u . Any chance someone can migrate it to Polymer 1.0?
> @ThaumRystra Stefan?

This got put on the back-burner for me, since I delayed migrating one of my projects to 1.0 for a bunch of other reasons. I'll take a look at it again today.

> Which package are you using to get polymer@1.0?

@splendido I'm using Bower to install Polymer 1.0 and `differential:vulcanize` to get it imported, you can check out [this project](https://github.com/ThaumRystra/meteor-polymer-seed) for an example of Polymer 1.0 running in Meteor. differential:vulcanize should be updated to run on Meteor 1.2 soon.
